version: '3.6'

services:
  app:
    image: jesusgoku/serve-files:dev
    build:
      target: base
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file: ./.env
    command: yarn run dev
